"""
One-command project setup for a new machine.

Writes .env from the friend's PostgreSQL credentials, creates the database,
runs all Django migrations (creates every table), and seeds demo data.

Examples:
  python setup_from_credentials.py --db-name orphan_dbase --db-user postgres --db-password secret --db-host localhost --db-port 5432
  python setup_from_credentials.py
      (interactive prompts)
"""

from __future__ import annotations

import argparse
import os
import secrets
import subprocess
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent
ENV_PATH = BACKEND_DIR / ".env"
EXAMPLE_PATH = BACKEND_DIR / ".env.example"


def _prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    return value or default


def _venv_python() -> Path:
    if os.name == "nt":
        return BACKEND_DIR / "venv" / "Scripts" / "python.exe"
    return BACKEND_DIR / "venv" / "bin" / "python"


def _run(cmd: list[str], *, env: dict | None = None) -> None:
    print(f"\n> {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=BACKEND_DIR, env=env)
    if result.returncode != 0:
        raise SystemExit(f"Command failed with exit code {result.returncode}: {' '.join(cmd)}")


def write_env(
    *,
    db_name: str,
    db_user: str,
    db_password: str,
    db_host: str,
    db_port: str,
) -> None:
    secret = secrets.token_urlsafe(48)
    content = f"""# Auto-generated by setup_from_credentials.py — do not commit this file.
SECRET_KEY={secret}
DEBUG=True

DB_NAME={db_name}
DB_USER={db_user}
DB_PASSWORD={db_password}
DB_HOST={db_host}
DB_PORT={db_port}

# Console email is fine for local demo (OTP / newsletter printed in terminal).
EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=465
EMAIL_USE_SSL=True
EMAIL_USE_TLS=False
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=

STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
"""
    ENV_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {ENV_PATH}")


def ensure_venv_and_deps() -> Path:
    py = _venv_python()
    if not py.exists():
        print("Creating virtual environment...")
        _run([sys.executable, "-m", "venv", str(BACKEND_DIR / "venv")])
        py = _venv_python()
        if not py.exists():
            raise SystemExit("Could not create venv. Install Python 3.12+ and retry.")

    print("Installing Python packages...")
    _run([str(py), "-m", "pip", "install", "--upgrade", "pip"])
    _run([str(py), "-m", "pip", "install", "-r", "requirements.txt"])
    return py


def create_database(py: Path) -> None:
    print("Creating PostgreSQL database if it does not exist...")
    _run([str(py), "create_db.py"])


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create .env, PostgreSQL database, tables, and demo data."
    )
    parser.add_argument("--db-name", default="", help="PostgreSQL database name")
    parser.add_argument("--db-user", default="", help="PostgreSQL username")
    parser.add_argument("--db-password", default="", help="PostgreSQL password")
    parser.add_argument("--db-host", default="", help="PostgreSQL host (usually localhost)")
    parser.add_argument("--db-port", default="", help="PostgreSQL port (usually 5432)")
    parser.add_argument(
        "--skip-seed",
        action="store_true",
        help="Only create DB + migrate; do not load demo users/data",
    )
    parser.add_argument(
        "--skip-deps",
        action="store_true",
        help="Assume venv + packages already installed",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    print("=" * 60)
    print("OESTS backend setup — PostgreSQL credentials")
    print("=" * 60)

    db_name = args.db_name or _prompt("DB name", "orphan_dbase")
    db_user = args.db_user or _prompt("DB user", "postgres")
    db_password = args.db_password or _prompt("DB password")
    db_host = args.db_host or _prompt("DB host", "localhost")
    db_port = args.db_port or _prompt("DB port", "5432")

    if not db_password:
        raise SystemExit("DB password is required.")

    write_env(
        db_name=db_name,
        db_user=db_user,
        db_password=db_password,
        db_host=db_host,
        db_port=db_port,
    )

    if args.skip_deps and _venv_python().exists():
        py = _venv_python()
    else:
        py = ensure_venv_and_deps()

    # Ensure create_db / manage.py see the new .env
    env = os.environ.copy()
    env["DB_NAME"] = db_name
    env["DB_USER"] = db_user
    env["DB_PASSWORD"] = db_password
    env["DB_HOST"] = db_host
    env["DB_PORT"] = db_port

    create_database(py)
    print("Running migrations (creating all tables)...")
    _run([str(py), "manage.py", "migrate"], env=env)
    if not args.skip_seed:
        print("Seeding demo data...")
        _run([str(py), "manage.py", "seed_demo_data"], env=env)

    print()
    print("=" * 60)
    print("Database setup complete.")
    print(f"  Database : {db_name}")
    print(f"  Host     : {db_host}:{db_port}")
    print()
    print("Start backend:")
    if os.name == "nt":
        print(r"  venv\Scripts\python.exe manage.py runserver")
    else:
        print("  venv/bin/python manage.py runserver")
    print()
    print("Demo logins:")
    print("  Admin    admin@gmail.com / admin@123")
    print("  Donor    donor1@gmail.com / Donor@123")
    print("  School   school1@gmail.com / School@123")
    print("  Guardian guardian1@gmail.com / Guardian@123")
    print("=" * 60)


if __name__ == "__main__":
    main()
